"""Make primary_contact optional

Revision ID: 082e82203992
Revises: 80f386a1a321
Create Date: 2025-11-08 13:01:09.582755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082e82203992'
down_revision = '80f386a1a321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('primary_contact',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('primary_contact',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
