"""Initial migration

Revision ID: ff0fd127ce26
Revises: 
Create Date: 2025-11-14 04:20:59.408175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0fd127ce26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('category1', sa.String(length=100), nullable=True),
    sa.Column('category2', sa.String(length=100), nullable=True),
    sa.Column('category3', sa.String(length=100), nullable=True),
    sa.Column('category4', sa.String(length=100), nullable=True),
    sa.Column('category5', sa.String(length=100), nullable=True),
    sa.Column('category6', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rate_impost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_temp_password', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_occupant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.String(length=5), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_primary_contact', sa.String(length=100), nullable=False),
    sa.Column('business_secondary_contact', sa.String(length=100), nullable=True),
    sa.Column('business_website', sa.String(length=200), nullable=True),
    sa.Column('business_email', sa.String(length=120), nullable=True),
    sa.Column('owner_primary_contact', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('house_no', sa.String(length=50), nullable=True),
    sa.Column('owner_email', sa.String(length=120), nullable=True),
    sa.Column('electoral_area', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('ghanapost_gps', sa.String(length=50), nullable=True),
    sa.Column('landmark', sa.String(length=200), nullable=True),
    sa.Column('division_no', sa.String(length=50), nullable=False),
    sa.Column('property_account_no', sa.String(length=50), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('display_category', sa.String(length=100), nullable=False),
    sa.Column('category1', sa.String(length=100), nullable=True),
    sa.Column('category2', sa.String(length=100), nullable=True),
    sa.Column('category3', sa.String(length=100), nullable=True),
    sa.Column('category4', sa.String(length=100), nullable=True),
    sa.Column('category5', sa.String(length=100), nullable=True),
    sa.Column('category6', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_occupant', schema=None) as batch_op:
        batch_op.create_index('idx_business_electoral_area', ['electoral_area'], unique=False)
        batch_op.create_index('idx_business_town', ['town'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_occupant_account_no'), ['account_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_business_occupant_business_id'), ['business_id'], unique=True)

    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_contact', sa.String(length=100), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('house_no', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('electoral_area', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('ghanapost_gps', sa.String(length=50), nullable=True),
    sa.Column('landmark', sa.String(length=200), nullable=True),
    sa.Column('block_no', sa.String(length=50), nullable=False),
    sa.Column('parcel_no', sa.String(length=50), nullable=False),
    sa.Column('division_no', sa.String(length=50), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('property_class', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('use_code', sa.String(length=50), nullable=False),
    sa.Column('valuation_status', sa.String(length=50), nullable=False),
    sa.Column('rateable_value', sa.Float(), nullable=False),
    sa.Column('rate_impost', sa.Float(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('supporting_doc1', sa.String(length=200), nullable=True),
    sa.Column('supporting_doc2', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index('idx_property_electoral_area', ['electoral_area'], unique=False)
        batch_op.create_index('idx_property_town', ['town'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_account_no'), ['account_no'], unique=True)

    op.create_table('temporary_password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('temp_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bop_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_occupant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    with op.batch_alter_table('bop_invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bop_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bop_invoice_year'), ['year'], unique=False)

    op.create_table('property_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('rateable_value', sa.Float(), nullable=False),
    sa.Column('rate_impost', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    with op.batch_alter_table('property_invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_invoice_year'), ['year'], unique=False)

    op.create_table('invoice_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_invoice_id', sa.Integer(), nullable=True),
    sa.Column('business_invoice_id', sa.Integer(), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('adjustment_amount', sa.Float(), nullable=False),
    sa.Column('new_amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supporting_document', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['business_invoice_id'], ['bop_invoice.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['property_invoice_id'], ['property_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_invoice_id', sa.Integer(), nullable=True),
    sa.Column('business_invoice_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('gcr_number', sa.String(length=50), nullable=True),
    sa.Column('valuation_number', sa.String(length=50), nullable=True),
    sa.Column('paid_by', sa.String(length=100), nullable=False),
    sa.Column('payer_name', sa.String(length=100), nullable=True),
    sa.Column('payer_phone', sa.String(length=20), nullable=True),
    sa.Column('sender_mobile_number', sa.String(length=20), nullable=True),
    sa.Column('mobile_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('cheque_name', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('cheque_photo', sa.String(length=200), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_invoice_id'], ['bop_invoice.id'], ),
    sa.ForeignKeyConstraint(['property_invoice_id'], ['property_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('invoice_adjustment')
    with op.batch_alter_table('property_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_invoice_year'))
        batch_op.drop_index(batch_op.f('ix_property_invoice_status'))

    op.drop_table('property_invoice')
    with op.batch_alter_table('bop_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bop_invoice_year'))
        batch_op.drop_index(batch_op.f('ix_bop_invoice_status'))

    op.drop_table('bop_invoice')
    op.drop_table('temporary_password')
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_account_no'))
        batch_op.drop_index('idx_property_town')
        batch_op.drop_index('idx_property_electoral_area')

    op.drop_table('property')
    op.drop_table('password_reset_token')
    with op.batch_alter_table('business_occupant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_occupant_business_id'))
        batch_op.drop_index(batch_op.f('ix_business_occupant_account_no'))
        batch_op.drop_index('idx_business_town')
        batch_op.drop_index('idx_business_electoral_area')

    op.drop_table('business_occupant')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('otp_verification')
    # ### end Alembic commands ###
